### ISSUE TITLE
A user can create, edit, and delete a gene set

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/single-cell#15] opened 2020-08-10 13:57 UTC
New user experience: Consumers can download, create, edit, and delete persistent, single-user gene sets in cellxgene.

Creating a gene set
1. A user should be able to create a new gene set from the workspace
2. A user should be able to name their gene set (same rules as naming for a category - no leading or trailing spaces, alphanumeric and limited special characters allowed (-_.)
3. A user should be able to create a gene set by adding a single gene (AP3D1), a comma delimited list of genes (AP3D1, PNMA3, KAT8, etc), or import a csv in the correct data format

Editting a gene set
4. A user should be able to add a gene to a gene set
5. A user should be able to remove a gene from a gene set
6. A user should be able to add a comment (free text field) to a specific gene in order to keep track of why they are including the gene in a gene set
7. A user should be able to edit the name of their gene set

Deleting a gene set
8. A user should be able to delete a gene set

**Out of Scope**
The following features that are out of scope for initial staging:
1. Uploading a geneset with its own custom distribution (we've heard this request from Valentine and Bruce Aronow, its important but a good candidate for future improvement) 
2. Search/filter functionality for genes and gene sets (Spotify search bar is an example)
3. Re-ordering gene sets (we should consider this as we think about heatmaps)
4. Including standard / precomputed gene sets

**Comment by ambrosejcarr** [comment] 2020-09-08 14:23
@vals noted it's important that gene sets (and genes in gene sets?) can be **annotated** with a short description. This could explain the context they were generated in ("taken from paper xzy", "differential expression between cluster 4 & 9 in datasets abc", etc).

**Comment by ambrosejcarr** [comment] 2020-09-08 14:39
Bruce Aronow noted that it's important that scientists can define their own gene set summaries, which may use weighting metrics other than our default (currently: average). This means that a gene set that is imported should optionally associate with an expression vector.

**Comment by signechambers1** [comment] 2021-02-03 21:51
Closing as a duplicate of cellxgene #2041

**Closed by signechambers1** 2021-02-03 21:51 UTC
Labels: design me!, epic
