### ISSUE TITLE
Validation of integration methodology

### ISSUE THREAD

**Issue by ainfeld** [chanzuckerberg/single-cell#483] opened 2023-07-06 22:27 UTC

**Comment by maniarathi** [comment] 2023-08-08 00:38
Hey @ainfeld -- I think this is a duplicate of #472 (https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/472). Is that correct or does this work refer to something else? Thanks!

**Comment by ainfeld** [comment] 2023-08-08 13:55
@maniarathi that might be, I would check with Bailey

**Comment by pancakesforlife** [comment] 2023-08-09 14:59
Yes this was made before anyone was assigned to this project. Will (attempt to) close!

**Closed by pancakesforlife** 2023-08-09 14:59 UTC
